### ISSUE TITLE
Example throws runtime error

### ISSUE THREAD

**Issue by DaOnlyOwner** [TheLartians/PEGParser#53]
Hello ;)
Building the examples works fine, however when I want to run the examples, the program throws an error in line 24 of python_identation.cpp: "string_view subscript out of range". I trace it back to State::current(). I am using MSVC (c++17 standard), tried Clang and it doesn't work too. 
The version of the lib is v2.0. 

Here is how it looks for me.
![grafik](https://user-images.githubusercontent.com/11295581/84673865-85699d80-af2a-11ea-8eb3-f4ca9b576ff4.png)

Any ideas?

**Comment by TheLartians** [comment]
Hey, thanks for the report!
I was wondering what was causing the CI failure under windows and hopefully found the bug thanks to the provided trace. I'm preparing a [PR](#54) that will hopefully fix the issue.

**Comment by TheLartians** [comment]
Hey, I've merged the PR with master as the Windows CI tests now pass. Could you check if this also fixed your issue with the examples?

**Comment by DaOnlyOwner** [comment]
Okay, checking it now!

**Comment by DaOnlyOwner** [comment]
Alright, it evaulates correctly. Thanks for the fast response ;)

**Comment by TheLartians** [comment]
Great, thanks for the report and traceback ;-)
