### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by DaOnlyOwner** [TheLartians/PEGParser#55]
Hello again ;)

I have a question regarding error handling: Is it possible to provide custom error messages when a syntax error is found in the given input? 

Right now the error messages are not really useful by its own (i.e. "syntax error at character 27...")

**Comment by TheLartians** [comment]
Hey, yeah first of all let me apologise for not adding better documentation yet, I haven't found the time yet to properly maintain this project.

There are currently two ways to handle errors:

- You let your program run and catch the exception that is thrown when a syntax error is encountered. The captured `SyntaxError` class itself contains the virtual parse tree of the rule that was attempted to be parsed, which might provide useful error information. You can see the [examples](https://github.com/TheLartians/PEGParser/blob/09784151e4e06f7b90954e59a24284a4700fb99b/example/calculator.cpp#L63) to see how to output information.
- You split your program into a parsing and interpretation step and do manual error handling. I would recommend looking at the [`run` method's implementation](https://github.com/TheLartians/PEGParser/blob/09784151e4e06f7b90954e59a24284a4700fb99b/include/peg_parser/interpreter.h#L162) to see how those steps are performed.

Eventually I hope to update this project and give it proper documentation. Until then feel free to ask here!
