### ISSUE TITLE
Problems with parsing rule using * or +

### ISSUE THREAD

**Issue by jteuber** [TheLartians/PEGParser#57]
Hi there!
This might just be me being an idiot, but I'm trying to write a parser for PlantUML files and I'm getting stuck pretty early in the process.
I can parse no element or a single class, interface, entity, whatever just fine with my current grammar, but not more. This is what I have, simplified to just the class:

```
peg_parser::ParserGenerator<void, PlantUML&> g;
g.setSeparator(g["Whitespace"] << "[\t \n]");
g["Identifier"] << "[a-zA-Z] [a-zA-Z0-9_]*";

// // elements
g["Class"] << "'class' Identifier" >> [](auto e, auto& p) { p.elements.push_back(PlantUML::Element{PlantUML::Element::Type::Class, e[0].string()}); };

// diagram
g["Start"] << "'@startuml'";
g["End"] << "'@enduml'";
g["Diagram"] << "Start Class* End";

g.setStart(g["Diagram"]);
```

This is the test that fails already (`Parser` just wraps the `ParserGenerator` with the rules):

```
static constexpr auto two_classes_puml = 
"@startuml\
class           class\
class           class2\
@enduml";

TEST_CASE( "diagram with all simple elements is parsed", "[Parser]" ) {
    Parser parser;
    PlantUML r = parser.parse(two_classes_puml);

    REQUIRE(r.elements.size() == 2);
}
```

Do you have any idea what I'm doing wrong here?

**Comment by jteuber** [comment]
Ok, scratch that, I'm dumb. I forgot to add `\n` to the end of all lines in the tests so there was no separation between the symbols.

**Comment by TheLartians** [comment]
Heh glad you figured it out! I'd always recommend using multiline string literals for such cases:

```cpp
R"(
@startuml
class           class
class           class2
@enduml
)"
```

**Comment by jteuber** [comment]
Oh yes, good point! Haven't actually seen those before. Thanks for the hint!
